apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: firstpod
spec:
    containers:
      - name: nginx
        image: nginx:latest
      - name: ubuntu
        image: ubuntu:latest
        command: ["sleep", "infinity"]
